repositories:
  - path: "D:/projects/sienar/Sandboxes/Bot-Snadbox-Launchpad"
  - path: "M:/drives/mike.pustovalov/YandexDisk/vaults/sith-shared"
  - path: "M:/drives/mike.pustovalov/YandexDisk/vaults/solar"
  - path: "M:/drives/mike.pustovalov/YandexDisk/vaults/trainz"
